# Generated by Django 3.0.3 on 2020-02-21 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0002_auto_20200221_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='air.Article'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='contnent',
            field=models.CharField(max_length=140),
        ),
    ]
