# Generated by Django 3.0.3 on 2020-02-21 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0003_auto_20200221_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='contnent',
            new_name='content',
        ),
    ]
